# Conda environment file for MLOps Drug Repurposing Project
# 
# This file allows users to create the exact conda environment with all dependencies.
# Usage: conda env create -f environment.yml

name: mlops-drug-repurposing

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  # Python version
  - python=3.10

  # Core scientific computing
  - numpy>=1.26.0
  - pandas>=2.0.0
  - scipy>=1.15.0
  - scikit-learn>=1.7.0

  # Deep learning
  - pytorch>=2.7.0
  - torchvision>=0.22.0
  - pytorch-geometric>=2.5.0

  # Cheminformatics
  - rdkit>=2022.09.0

  # Data visualization
  - matplotlib>=3.10.0
  - seaborn>=0.13.0
  - plotly>=5.0.0

  # Development tools
  - jupyter
  - jupyterlab
  - ipywidgets

  # System dependencies
  - git
  - curl
  - wget

  # Pip dependencies that are not available via conda
  - pip

  - pip:
    # MLflow and related
    - mlflow>=3.1.0,<4.0.0
    - mlflow-skinny>=3.1.0,<4.0.0
    
    # DVC and data versioning
    - dvc[s3]>=3.61.0,<4.0.0
    - dvc-data>=3.16.0,<4.0.0
    - dvc-objects>=5.1.0,<6.0.0
    - dvc-render>=1.0.0,<2.0.0
    - dvc-studio-client>=0.21.0,<1.0.0
    
    # AWS integration
    - boto3>=1.39.0,<2.0.0
    - botocore>=1.39.0,<2.0.0
    - s3fs>=2025.5.0,<2026.0.0
    
    # Web framework
    - fastapi>=0.116.0,<1.0.0
    - uvicorn>=0.35.0,<1.0.0
    - starlette>=0.47.0,<1.0.0
    
    # Configuration and utilities
    - pyyaml>=6.0.0
    - click>=8.2.0,<9.0.0
    - typer>=0.16.0,<1.0.0
    - pydantic>=2.11.0,<3.0.0
    - requests>=2.32.0,<3.0.0
    - tqdm>=4.67.0,<5.0.0
    
    # Database
    - sqlalchemy>=2.0.0,<3.0.0
    - alembic>=1.16.0,<2.0.0
    - pyarrow>=20.0.0,<21.0.0
    
    # Model interpretation
    - shap>=0.45.0,<1.0.0
    - lime>=0.2.0,<1.0.0
    
    # Data validation
    - great-expectations>=0.18.0,<1.0.0
    - pandera>=0.17.0,<1.0.0
    
    # Development tools (optional)
    - pytest>=7.0.0,<8.0.0
    - black>=24.0.0
    - flake8>=6.0.0,<7.0.0
    - mypy>=1.0.0,<2.0.0
    - pre-commit>=3.0.0,<4.0.0

variables:
  # Environment variables
  KMP_DUPLICATE_LIB_OK: "TRUE"
  PYTHONPATH: $CONDA_PREFIX
  MLFLOW_TRACKING_URI: "file://./mlruns"