output "vpc_id" {
  description = "ID of the VPC"
  value       = aws_vpc.main.id
}

output "vpc_cidr_block" {
  description = "CIDR block of the VPC"
  value       = aws_vpc.main.cidr_block
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = aws_subnet.public[*].id
}

output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = aws_subnet.private[*].id
}

output "eks_cluster_id" {
  description = "EKS cluster ID"
  value       = aws_eks_cluster.main.id
}

output "eks_cluster_arn" {
  description = "EKS cluster ARN"
  value       = aws_eks_cluster.main.arn
}

output "eks_cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = aws_eks_cluster.main.endpoint
}

output "eks_cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value       = aws_eks_cluster.main.vpc_config[0].cluster_security_group_id
}

output "eks_cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = aws_eks_cluster.main.certificate_authority[0].data
}

output "s3_data_bucket_name" {
  description = "Name of the S3 bucket for data storage"
  value       = aws_s3_bucket.data.bucket
}

output "s3_models_bucket_name" {
  description = "Name of the S3 bucket for model storage"
  value       = aws_s3_bucket.models.bucket
}

output "s3_artifacts_bucket_name" {
  description = "Name of the S3 bucket for artifacts storage"
  value       = aws_s3_bucket.artifacts.bucket
}

output "rds_mlflow_endpoint" {
  description = "RDS instance endpoint for MLflow"
  value       = aws_db_instance.mlflow.endpoint
  sensitive   = true
}

output "rds_airflow_endpoint" {
  description = "RDS instance endpoint for Airflow"
  value       = aws_db_instance.airflow.endpoint
  sensitive   = true
}

output "mlflow_db_secret_arn" {
  description = "ARN of the secret containing MLflow database credentials"
  value       = aws_secretsmanager_secret.mlflow_db.arn
}

output "airflow_db_secret_arn" {
  description = "ARN of the secret containing Airflow database credentials"
  value       = aws_secretsmanager_secret.airflow_db.arn
}

output "cloudwatch_dashboard_url" {
  description = "URL to the CloudWatch dashboard"
  value       = "https://${var.aws_region}.console.aws.amazon.com/cloudwatch/home?region=${var.aws_region}#dashboards:name=${aws_cloudwatch_dashboard.mlops_dashboard.dashboard_name}"
}

output "environment" {
  description = "Environment name"
  value       = var.environment
}

output "resource_prefix" {
  description = "Resource naming prefix used across all resources"
  value       = "${var.project_name}-${var.environment}"
}

output "sns_alerts_topic_arn" {
  description = "ARN of the SNS topic for alerts"
  value       = aws_sns_topic.mlops_alerts.arn
}

# Kubernetes configuration
output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value = {
    cluster_name = aws_eks_cluster.main.name
    endpoint     = aws_eks_cluster.main.endpoint
    region       = var.aws_region
  }
}